### ISSUE TITLE
What to do if you get an error

### ISSUE THREAD

**Issue by qualk** [LocalsGitHub/Discord-Logger-Builder#4]
If you get an error:
1: Use [my](https://github.com/qualk/Discord-Logger-Builder) fork (unless it is already merged)
2: Uninstall `typing` (`python -m pip remove typing`) and try again

If still not working, [make an issue in my repo](https://github.com/qualk/Discord-Logger-Builder/issues/), unless the PR has been merged.

**Comment by LocalsGitHub** [comment]
I will merge your fork, once the right changes have been made.
